PackageIdentifier: GitSetup.CLI
PackageVersion: 0.0.1
PackageName: Git Setup CLI
Publisher: ApexV2
License: MIT
ShortDescription: CLI tool to setup git repositories with support for Winget, Scoop, and Chocolatey
Tags:
  - git
  - cli
  - setup
InstallerType: exe
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ApexV2/git-setup/releases/download/v0.0.1/git-setup.exe
    InstallerSha256: 588a30a779508558e9bf3572c5f8b696201944686d1dcac4e7fa36b062b356d2
    Scope: user
ManifestType: singleton
ManifestVersion: 1.0.0 