on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: build using npm
              run: |
                pnpm install
                pnpm run build

            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: exe
                path: dist/*.exe
