name: lint

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]
        branches: [dev, main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: use Node.js
              uses: actions/setup-node@v2
              with:
                  node_version: "20.x"

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Install eslint and prettier
              run: pnpm install eslint prettier

            - name: Run linters
              run: pnpm eslint . && pnpm prettier .
